// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'treatment_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$TreatmentModelImpl _$$TreatmentModelImplFromJson(Map<String, dynamic> json) =>
    _$TreatmentModelImpl(
      id: (json['id'] as num?)?.toInt(),
      caseDefinition: json['case_definition'] as String?,
      tbSite: json['tb_site'] as String?,
      caseHistory: json['case_history'] as String?,
      drugSensitive: json['drug_sensitive'] as String?,
      diagnosisStatus: json['diagnosis_status'] as String?,
      ihvDate: fromJsonToDateTime(json['ihv_date'] as String?),
      treatmentRegimen: json['treatment_regimen'] as String?,
      patientOccupation: json['patient_occupation'] as String?,
      treatmentSupporterName: json['treatment_supporter_name'] as String?,
      treatmentSupporterPosition:
          json['treatment_supporter_position'] as String?,
      treatmentSupporterPhone: json['treatment_supporter_phone'] as String?,
      treatmentSupporterPanchayat:
          json['treatmentSupporterPanchayat'] as String?,
      selectedTreatmentSupporterPanchayat:
          (json['treatment_supporter_panchayat'] as num?)?.toInt(),
      treatmentSupporterWard:
          (json['treatment_supporter_ward'] as num?)?.toInt(),
      ipStartDate: fromJsonToDateTime(json['ipt_start_date'] as String?),
      hivDone: json['hiv_done'] as String?,
      hivResult: json['hiv_result'] as String?,
      hivDate: fromJsonToDateTime(json['hiv_date'] as String?),
      hbDone: json['hb_done'] as String?,
      hbResult: (json['hb_result'] as num?)?.toDouble(),
      hbDate: fromJsonToDateTime(json['hb_date'] as String?),
      bloodSugarDone: json['blood_sugar_done'] as String?,
      bloodSugarResult: (json['blood_sugar_result'] as num?)?.toInt(),
      bloodSugarDate: fromJsonToDateTime(json['blood_sugar_date'] as String?),
      alcohol: json['alcohol'] as String?,
      tobaccoConsumption: json['tb_consumption'] as String?,
      nutritionScreening: json['nutrition_screening'] as String?,
      nutritionEligibility: json['nutrition_eligibility'] as String?,
      screeningDateNutrition:
          fromJsonToDateTime(json['nutrition_screening_date'] as String?),
      nutritionLinkage: json['nutrition_linkage'] as String?,
      nutritionLinkageDate:
          fromJsonToDateTime(json['nutrition_linkage_date'] as String?),
      height: (json['height'] as num?)?.toInt(),
      weight: (json['weight'] as num?)?.toInt(),
      stage: json['stage'] as String?,
      ipfuDate: fromJsonToDateTime(json['ipfu_date'] as String?),
      ipfuAfbDone: json['ipfu_afb_done'] as String?,
      ipfuAfbLabNo: json['ip_followup_afb_lab_number'] as String?,
      ipfuAfbDate: fromJsonToDateTime(json['ipfu_afb_date'] as String?),
      ipfuAfbResult: json['ipfuAfbResult'] as String?,
      selectedIpfuAFBResult: (json['ipfu_afb_result'] as num?)?.toInt(),
      ipfuNaatTest: json['ip_followup_nat_test'] as String?,
      ipfuNaatResult: json['ipfuNaatResult'] as String?,
      selectedIpfuNaatResult:
          (json['ip_followup_naat_result'] as num?)?.toInt(),
      ipfuLabNo: json['ip_followup_lab_number'] as String?,
      ipfuChestXray: json['ipfu_chest_xray'] as String?,
      ipfuNutritionSupport: json['ipfu_nutrition_support'] as String?,
      cpDate: fromJsonToDateTime(json['cp_date'] as String?),
      cpAfbDone: json['cp_afb_done'] as String?,
      cpAfbLabNo: json['cp_afb_lab_number'] as String?,
      cpAfbDate: fromJsonToDateTime(json['cp_afb_date'] as String?),
      cpAfbResult: json['cpAfbResult'] as String?,
      selectedCpAFBResult: (json['cp_afb_result'] as num?)?.toInt(),
      cpNaatTest: json['cp_naat_test'] as String?,
      cpNaatResult: json['cpNaatResult'] as String?,
      selectedCpNaatResult: (json['cp_naat_result'] as num?)?.toInt(),
      cpLabNo: json['cp_lab_no'] as String?,
      cpChestXray: json['cp_chest_xray'] as String?,
      cpNutritionSupport: json['cp_nutrition_support'] as String?,
    );

Map<String, dynamic> _$$TreatmentModelImplToJson(
        _$TreatmentModelImpl instance) =>
    <String, dynamic>{
      'case_definition': instance.caseDefinition,
      'tb_site': instance.tbSite,
      'case_history': instance.caseHistory,
      'drug_sensitive': instance.drugSensitive,
      'diagnosis_status': instance.diagnosisStatus,
      'ihv_date': _dateTimeToJson(instance.ihvDate),
      'treatment_regimen': instance.treatmentRegimen,
      'patient_occupation': instance.patientOccupation,
      'treatment_supporter_name': instance.treatmentSupporterName,
      'treatment_supporter_position': instance.treatmentSupporterPosition,
      'treatment_supporter_phone': instance.treatmentSupporterPhone,
      'treatment_supporter_panchayat':
          instance.selectedTreatmentSupporterPanchayat,
      'treatment_supporter_ward': instance.treatmentSupporterWard,
      'ipt_start_date': _dateTimeToJson(instance.ipStartDate),
      'hiv_done': instance.hivDone,
      'hiv_result': instance.hivResult,
      'hiv_date': _dateTimeToJson(instance.hivDate),
      'hb_done': instance.hbDone,
      'hb_result': instance.hbResult,
      'hb_date': _dateTimeToJson(instance.hbDate),
      'blood_sugar_done': instance.bloodSugarDone,
      'blood_sugar_result': instance.bloodSugarResult,
      'blood_sugar_date': _dateTimeToJson(instance.bloodSugarDate),
      'alcohol': instance.alcohol,
      'tb_consumption': instance.tobaccoConsumption,
      'nutrition_screening': instance.nutritionScreening,
      'nutrition_eligibility': instance.nutritionEligibility,
      'nutrition_screening_date':
          _dateTimeToJson(instance.screeningDateNutrition),
      'nutrition_linkage': instance.nutritionLinkage,
      'nutrition_linkage_date': _dateTimeToJson(instance.nutritionLinkageDate),
      'height': instance.height,
      'weight': instance.weight,
      'stage': instance.stage,
      'ipfu_date': _dateTimeToJson(instance.ipfuDate),
      'ipfu_afb_done': instance.ipfuAfbDone,
      'ip_followup_afb_lab_number': instance.ipfuAfbLabNo,
      'ipfu_afb_date': _dateTimeToJson(instance.ipfuAfbDate),
      'ipfu_afb_result': instance.selectedIpfuAFBResult,
      'ip_followup_nat_test': instance.ipfuNaatTest,
      'ip_followup_naat_result': instance.selectedIpfuNaatResult,
      'ip_followup_lab_number': instance.ipfuLabNo,
      'ipfu_chest_xray': instance.ipfuChestXray,
      'ipfu_nutrition_support': instance.ipfuNutritionSupport,
      'cp_date': _dateTimeToJson(instance.cpDate),
      'cp_afb_done': instance.cpAfbDone,
      'cp_afb_lab_number': instance.cpAfbLabNo,
      'cp_afb_date': _dateTimeToJson(instance.cpAfbDate),
      'cp_afb_result': instance.selectedCpAFBResult,
      'cp_naat_test': instance.cpNaatTest,
      'cp_naat_result': instance.selectedCpNaatResult,
      'cp_lab_no': instance.cpLabNo,
      'cp_chest_xray': instance.cpChestXray,
      'cp_nutrition_support': instance.cpNutritionSupport,
    };
