// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1lWYdNS2OaYr2SSL92K5cjR8tXZg7b2g',
    appId: '1:762173822440:web:a6f4f4e52a87b62d80805d',
    messagingSenderId: '762173822440',
    projectId: 'tatpar-acf',
    authDomain: 'tatpar-acf.firebaseapp.com',
    storageBucket: 'tatpar-acf.appspot.com',
    measurementId: 'G-WR1DX5WMQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BalbnWbYbYqOe3tylnWLJLtu4s4Fs08',
    appId: '1:762173822440:android:bde5b3247b9c87f980805d',
    messagingSenderId: '762173822440',
    projectId: 'tatpar-acf',
    storageBucket: 'tatpar-acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhaXTbuzjYfQHxCpSwJGAggywncVGaOAI',
    appId: '1:762173822440:ios:e4c59ad91d9f360d80805d',
    messagingSenderId: '762173822440',
    projectId: 'tatpar-acf',
    storageBucket: 'tatpar-acf.appspot.com',
    iosBundleId: 'com.example.tatparAcf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhaXTbuzjYfQHxCpSwJGAggywncVGaOAI',
    appId: '1:762173822440:ios:bb5708a5fc834ccb80805d',
    messagingSenderId: '762173822440',
    projectId: 'tatpar-acf',
    storageBucket: 'tatpar-acf.appspot.com',
    iosBundleId: 'com.example.tatparAcf.RunnerTests',
  );
}
