// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy8y_KWLRo8KTU_DOLclQMGhBNH9isRU4',
    appId: '1:449590885521:web:fcee136c1e4fc6258b1330',
    messagingSenderId: '449590885521',
    projectId: 'tatpar-orange',
    authDomain: 'tatpar-orange.firebaseapp.com',
    storageBucket: 'tatpar-orange.firebasestorage.app',
    measurementId: 'G-41GVPQF4EJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADiOLR_xmDceXGlKaTd4sPLRIYzeOYMPM',
    appId: '1:449590885521:android:4638020c226f94838b1330',
    messagingSenderId: '449590885521',
    projectId: 'tatpar-orange',
    storageBucket: 'tatpar-orange.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEPOwrMyRhnWKbtWuE6tkgmFep4t3HKrE',
    appId: '1:449590885521:ios:837423bebde0dd188b1330',
    messagingSenderId: '449590885521',
    projectId: 'tatpar-orange',
    storageBucket: 'tatpar-orange.firebasestorage.app',
    iosBundleId: 'com.mylabs.tatparAcf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEPOwrMyRhnWKbtWuE6tkgmFep4t3HKrE',
    appId: '1:449590885521:ios:837423bebde0dd188b1330',
    messagingSenderId: '449590885521',
    projectId: 'tatpar-orange',
    storageBucket: 'tatpar-orange.firebasestorage.app',
    iosBundleId: 'com.mylabs.tatparAcf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy8y_KWLRo8KTU_DOLclQMGhBNH9isRU4',
    appId: '1:449590885521:web:698b2f46d7bd980f8b1330',
    messagingSenderId: '449590885521',
    projectId: 'tatpar-orange',
    authDomain: 'tatpar-orange.firebaseapp.com',
    storageBucket: 'tatpar-orange.firebasestorage.app',
    measurementId: 'G-BH48RXH8PZ',
  );

}