// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZFRmdzCbpqvHF9SG9tKbdNtnTnx6JeC8',
    appId: '1:555188132765:web:524a6e50dd6906cd712d74',
    messagingSenderId: '555188132765',
    projectId: 'tatpar-acf-flutter',
    authDomain: 'tatpar-acf-flutter.firebaseapp.com',
    storageBucket: 'tatpar-acf-flutter.appspot.com',
    measurementId: 'G-WBGWK8FYTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtrN9Ndltn3s4mb8EC0MymPJbJEoDKcxw',
    appId: '1:555188132765:android:8d5b0dd8aff934b3712d74',
    messagingSenderId: '555188132765',
    projectId: 'tatpar-acf-flutter',
    storageBucket: 'tatpar-acf-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHGUcLViZ8s8bhphsabFwiikmVZVZ3WY',
    appId: '1:555188132765:ios:1f493d77529dee4f712d74',
    messagingSenderId: '555188132765',
    projectId: 'tatpar-acf-flutter',
    storageBucket: 'tatpar-acf-flutter.appspot.com',
    iosBundleId: 'com.example.tatparAcf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhaXTbuzjYfQHxCpSwJGAggywncVGaOAI',
    appId: '1:762173822440:ios:bb5708a5fc834ccb80805d',
    messagingSenderId: '762173822440',
    projectId: 'tatpar-acf',
    storageBucket: 'tatpar-acf.appspot.com',
    iosBundleId: 'com.example.tatparAcf.RunnerTests',
  );
}